// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrqzmjjpnylcmunyaovj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhycXptampwbnlsY211bnlhb3ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NTc2MTEsImV4cCI6MjA2OTUzMzYxMX0.46wLidJyg2b-2xP9G02MKQQ_TuHg2dN66850wGfSXH4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});