version: '3.9'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: idrac_orchestrator
      POSTGRES_USER: idrac_admin
      POSTGRES_PASSWORD: change-me
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - API_PORT=8080
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
